export const activityCategories = [
  // Business Analysis
  { id: "ba-req-gathering-prep", group: "Business Analysis", name: "Requirement gathering preparation" },
  { id: "ba-req-documentation", group: "Business Analysis", name: "Requirement documentation" },
  { id: "ba-brd", group: "Business Analysis", name: "Business Requirement Document creation" },
  { id: "ba-crd", group: "Business Analysis", name: "Change Request Document creation" },
  { id: "ba-srs", group: "Business Analysis", name: "Software Requirement Specification creation" },
  { id: "ba-usecase", group: "Business Analysis", name: "Use-case creation" },
  { id: "ba-userstory", group: "Business Analysis", name: "User-story creation" },
  { id: "ba-acceptance-criteria", group: "Business Analysis", name: "Acceptance-criteria preparation" },
  { id: "ba-process-flow", group: "Business Analysis", name: "Process-flow creation" },
  { id: "ba-api-req-analysis", group: "Business Analysis", name: "API requirement analysis" },
  { id: "ba-api-documentation", group: "Business Analysis", name: "API documentation" },
  { id: "ba-gap-analysis", group: "Business Analysis", name: "Gap analysis" },
  { id: "ba-impact-analysis", group: "Business Analysis", name: "Impact analysis" },
  { id: "ba-root-cause", group: "Business Analysis", name: "Root-cause analysis" },
  { id: "ba-meeting-prep", group: "Business Analysis", name: "Meeting preparation" },
  { id: "ba-mom", group: "Business Analysis", name: "Minutes of Meeting preparation" },
  { id: "ba-customer-comm", group: "Business Analysis", name: "Customer communication drafting" },
  { id: "ba-req-clarification", group: "Business Analysis", name: "Requirement clarification" },
  { id: "ba-test-scenario", group: "Business Analysis", name: "Test-scenario preparation" },
  { id: "ba-report-analysis", group: "Business Analysis", name: "Report analysis" },
  { id: "ba-data-analysis", group: "Business Analysis", name: "Data analysis" },
  { id: "ba-diagram", group: "Business Analysis", name: "Diagram creation" },
  { id: "ba-doc-review", group: "Business Analysis", name: "Document review" },
  { id: "ba-translation", group: "Business Analysis", name: "Translation and localization" },
  { id: "ba-audit-prep", group: "Business Analysis", name: "Audit preparation" },
  { id: "ba-compliance-doc", group: "Business Analysis", name: "Compliance-document preparation" },
  { id: "ba-research-competitor", group: "Business Analysis", name: "Research and competitor analysis" },
  // Presales
  { id: "ps-proposal-prep", group: "Presales", name: "Proposal preparation" },
  { id: "ps-rfp-response", group: "Presales", name: "Request for Proposal response" },
  { id: "ps-rfi-response", group: "Presales", name: "Request for Information response" },
  { id: "ps-solution-design", group: "Presales", name: "Solution design" },
  { id: "ps-solution-description", group: "Presales", name: "Solution-description preparation" },
  { id: "ps-scope-definition", group: "Presales", name: "Scope definition" },
  { id: "ps-assumption-dependency", group: "Presales", name: "Assumption and dependency preparation" },
  { id: "ps-effort-estimation", group: "Presales", name: "Effort-estimation support" },
  { id: "ps-commercial-proposal", group: "Presales", name: "Commercial-proposal preparation" },
  { id: "ps-presentation-prep", group: "Presales", name: "Presentation preparation" },
  { id: "ps-demo-prep", group: "Presales", name: "Demo preparation" },
  { id: "ps-demo-data-gen", group: "Presales", name: "Demo-data generation" },
  { id: "ps-customer-usecase", group: "Presales", name: "Customer-use-case identification" },
  { id: "ps-market-research", group: "Presales", name: "Market research" },
  { id: "ps-competitor-comparison", group: "Presales", name: "Competitor comparison" },
  { id: "ps-product-positioning", group: "Presales", name: "Product-positioning preparation" },
  { id: "ps-technical-clarification", group: "Presales", name: "Technical clarification" },
  { id: "ps-tender-response", group: "Presales", name: "Tender-response preparation" },
  { id: "ps-exec-summary", group: "Presales", name: "Executive-summary preparation" },
  { id: "ps-customer-followup", group: "Presales", name: "Customer follow-up drafting" },
  { id: "ps-sales-pipeline-research", group: "Presales", name: "Sales-pipeline research" },
  { id: "ps-poc-prep", group: "Presales", name: "Proof-of-concept preparation" },
  { id: "ps-prototype-wireframe", group: "Presales", name: "Prototype or wireframe preparation" },
  { id: "ps-case-study", group: "Presales", name: "Case-study preparation" },
  { id: "ps-tech-architecture-explanation", group: "Presales", name: "Technical architecture explanation" },
];
