import { ApprovalStatus } from "../../generated/prisma/client";

export const knowledgeItems = [
  {
    id: "kb-1", title: "Turning a Client Meeting Recording into a Polished MoM in Under 30 Minutes",
    problemAddressed: "MoM preparation after client workshops routinely took 60-90 minutes and slipped to the next day.",
    activityCategoryId: "ba-mom", recommendedToolId: "tool-internal", assetId: "rp-mom-recap",
    approvedPrompt: "\"Given this meeting transcript and agenda, produce a Minutes of Meeting with sections: Attendees, Decisions, Action Items (owner + due date), Open Questions. Do not invent action items not discussed.\"",
    inputRequirements: ["Meeting recording or transcript", "Original agenda", "Attendee list"],
    workflowSteps: [
      "Record or transcribe the meeting (Otter.ai or native recorder).",
      "Paste transcript + agenda into the internal assistant with the approved prompt.",
      "Review the generated MoM against the agenda for completeness.",
      "Confirm action-item owners with the meeting organizer before sending.",
    ],
    humanReviewChecklist: ["All agenda items addressed", "Action items have a named owner", "No invented commitments", "Sensitive commercial terms redacted if distributing externally"],
    risksLimitations: ["Poor audio quality reduces transcript accuracy", "Cross-talk in large meetings can misattribute action items"],
    avgTimeSaved: 0.9, avgQualityImprovement: 25, successfulUses: 46, ownerId: "mgr-201", lastReviewedDate: new Date("2026-06-01"), version: "2.1", approvalStatus: ApprovalStatus.APPROVED,
    helpfulVotes: 27, notHelpfulVotes: 2,
  },
  {
    id: "kb-2", title: "Executive Summary Generator for Enterprise Proposals",
    problemAddressed: "Executive summaries were the last-minute bottleneck before proposal submission, often rushed.",
    activityCategoryId: "ps-exec-summary", recommendedToolId: "tool-claude", assetId: "rp-execsummary",
    approvedPrompt: "\"Summarize this proposal into a one-page executive summary for a non-technical buying committee. Lead with business outcomes, not features. Keep under 400 words.\"",
    inputRequirements: ["Full proposal draft (technical + commercial sections)", "Client business priorities noted from discovery calls"],
    workflowSteps: [
      "Finalize the technical and commercial sections first.",
      "Feed the full draft into Claude with the approved prompt.",
      "Check that business outcomes (not just features) lead the narrative.",
      "Have the account manager confirm tone matches the client relationship.",
    ],
    humanReviewChecklist: ["Business outcomes lead, not feature lists", "Pricing figures match the commercial section exactly", "No competitor names mentioned unless approved"],
    risksLimitations: ["Can overstate certainty on effort/timeline if source draft is still in flux"],
    avgTimeSaved: 1.3, avgQualityImprovement: 30, successfulUses: 14, ownerId: "mgr-203", lastReviewedDate: new Date("2026-05-01"), version: "1.4", approvalStatus: ApprovalStatus.APPROVED,
    helpfulVotes: 11, notHelpfulVotes: 1,
  },
  {
    id: "kb-3", title: "Generating Test Scenarios Directly from Requirement Documents",
    problemAddressed: "Test scenario drafting was repetitive and often missed edge cases under deadline pressure.",
    activityCategoryId: "ba-test-scenario", recommendedToolId: "tool-chatgpt", assetId: "rp-testscenario-gen",
    approvedPrompt: "\"From this SRS section, generate test scenarios covering happy path, boundary conditions, and negative cases. Group by requirement ID.\"",
    inputRequirements: ["Approved SRS or requirement section", "Any known edge cases from prior defects"],
    workflowSteps: [
      "Paste the approved requirement section (not draft/unapproved requirements).",
      "Generate scenarios grouped by requirement ID.",
      "Add any organization-specific edge cases the model would not know about.",
      "Cross-check scenario count against historical averages for similar modules.",
    ],
    humanReviewChecklist: ["Every requirement ID has at least one scenario", "Negative/edge cases included, not just happy path", "No scenario duplicates an existing regression test"],
    risksLimitations: ["Quality depends entirely on how complete the source requirement is"],
    avgTimeSaved: 1.4, avgQualityImprovement: 22, successfulUses: 19, ownerId: "mgr-201", lastReviewedDate: new Date("2026-01-23"), version: "1.2", approvalStatus: ApprovalStatus.APPROVED,
    helpfulVotes: 16, notHelpfulVotes: 1,
  },
  {
    id: "kb-4", title: "RFP Response Skeleton: From Blank Page to First Draft in Hours, Not Days",
    problemAddressed: "Large RFP responses consumed 3+ days of parallel effort across BA and Presales with inconsistent section quality.",
    activityCategoryId: "ps-rfp-response", recommendedToolId: "tool-claude", assetId: "rp-rfp-structure",
    approvedPrompt: "\"Given this RFP requirement list, generate a first-draft response section-by-section, flagging any requirement you are not confident about with [NEEDS SME REVIEW].\"",
    inputRequirements: ["Full RFP requirement list", "Past won-proposal references for tone", "Named SME per section for review"],
    workflowSteps: [
      "Split the RFP into sections and assign an SME reviewer per section upfront.",
      "Generate first drafts per section, always requesting [NEEDS SME REVIEW] flags.",
      "Route flagged sections to the named SME before compiling.",
      "Run a single final consistency pass across all sections.",
    ],
    humanReviewChecklist: ["Every [NEEDS SME REVIEW] flag resolved", "Technical claims verified against actual product capability", "Compliance/commercial terms reviewed by the deal owner"],
    risksLimitations: ["Multi-contributor drafts can drift in tone without a final consistency pass", "Not a substitute for domain sign-off on technical commitments"],
    avgTimeSaved: 8, avgQualityImprovement: 28, successfulUses: 6, ownerId: "mgr-203", lastReviewedDate: new Date("2026-03-07"), version: "1.0", approvalStatus: ApprovalStatus.APPROVED,
    helpfulVotes: 5, notHelpfulVotes: 0,
  },
  {
    id: "kb-5", title: "Competitor Snapshot Briefs for Fast-Moving Deals",
    problemAddressed: "Competitor research for time-sensitive deals was often skipped entirely due to time pressure.",
    activityCategoryId: "ps-competitor-comparison", recommendedToolId: "tool-perplexity", assetId: "rp-competitor-brief",
    approvedPrompt: "\"Produce a comparison table of these named competitors on pricing, deployment model, and key differentiators. Cite sources for every figure.\"",
    inputRequirements: ["Named competitor list (do not let the model guess who the competitors are)", "Deal timeline / urgency"],
    workflowSteps: [
      "Name the specific competitors - never let the model infer the competitive set.",
      "Generate the comparison table with mandatory citations.",
      "Spot-check any pricing or capability figure older than 6 months.",
      "Attach the brief to the opportunity record in CRM.",
    ],
    humanReviewChecklist: ["Every figure has a citation", "Citations are dated and independently opened, not just trusted", "No fabricated competitor features"],
    risksLimitations: ["Public pricing data ages quickly - always verify anything used in a live commercial negotiation"],
    avgTimeSaved: 2.2, avgQualityImprovement: 15, successfulUses: 11, ownerId: "mgr-204", lastReviewedDate: new Date("2026-04-01"), version: "1.3", approvalStatus: ApprovalStatus.APPROVED,
    helpfulVotes: 8, notHelpfulVotes: 2,
  },
  {
    id: "kb-6", title: "Why AI-Drafted CRD Sections Still Need a Fact-Check Pass",
    problemAddressed: "Two separate CRD submissions (OPT-2002, OPT-2049) showed the CRD template referencing outdated fee-cap rules, adding rework instead of avoiding it.",
    activityCategoryId: "ba-crd", recommendedToolId: "tool-chatgpt", assetId: "rp-crd-outline",
    approvedPrompt: "\"Draft the impact section of this Change Request Document using ONLY the attached current BRD and policy documents as source of truth. Do not use general banking knowledge for specific figures - flag any figure you cannot source.\"",
    inputRequirements: ["Current BRD (verify version/date before attaching)", "Current fee/policy reference document"],
    workflowSteps: [
      "Confirm you are attaching the current-version policy document, not a cached copy.",
      "Generate the draft with the source-only instruction.",
      "Verify every numeric figure against the attached source, not general knowledge.",
      "If any figure could not be sourced, resolve it manually before submitting.",
    ],
    humanReviewChecklist: ["Every monetary figure traced to a specific source document", "No figure relies on the model's general training knowledge", "Rollback/assumptions section reviewed by a second BA"],
    risksLimitations: ["This template is currently flagged Under Review after repeated factual-accuracy issues - use with extra scrutiny until re-approved."],
    avgTimeSaved: -0.1, avgQualityImprovement: -5, successfulUses: 9, ownerId: "mgr-202", lastReviewedDate: new Date("2026-07-12"), version: "1.1", approvalStatus: ApprovalStatus.UNDER_REVIEW,
    helpfulVotes: 4, notHelpfulVotes: 5,
  },
];
