import { Severity, UserGroup } from "../../generated/prisma/client";

export const notifications = [
  { id: "ntf-1", type: "Duplicate Entry", message: "OPT-2049 closely mirrors OPT-2002 (same employee, project, category, near-identical effort figures). Review before validating.", severity: Severity.MEDIUM, relatedId: "OPT-2049", date: new Date("2026-07-12"), audienceRoles: [UserGroup.LEAD_BSE, UserGroup.ADMIN], readBy: [] as string[] },
  { id: "ntf-2", type: "Abnormally High Claim", message: "OPT-2050 claims a 95% effort reduction (20h to 1h) with no evidence attached - well outside the historical range for requirement documentation.", severity: Severity.HIGH, relatedId: "OPT-2050", date: new Date("2026-07-15"), audienceRoles: [UserGroup.LEAD_BSE, UserGroup.MANAGEMENT, UserGroup.ADMIN], readBy: [] as string[] },
  { id: "ntf-3", type: "Missing Evidence", message: "OPT-2050 has no evidence attachment or supporting link despite claiming a high-value benefit.", severity: Severity.HIGH, relatedId: "OPT-2050", date: new Date("2026-07-15"), audienceRoles: [UserGroup.LEAD_BSE, UserGroup.ADMIN], readBy: [] as string[] },
  { id: "ntf-4", type: "Negative AI Benefit", message: "OPT-2010 (Solution Description, Gemini) was discarded - AI-introduced factual errors cost more rework time than manual drafting would have.", severity: Severity.HIGH, relatedId: "OPT-2010", date: new Date("2026-04-09"), audienceRoles: [UserGroup.LEAD_BSE, UserGroup.MANAGEMENT], readBy: [] as string[] },
  { id: "ntf-5", type: "Increasing Rework Trend", message: "CRD creation via the CRD Section Drafting Template has now shown factual-accuracy rework on 2 of 9 uses (OPT-2002, OPT-2049). Template flagged Under Review.", severity: Severity.MEDIUM, relatedId: "rp-crd-outline", date: new Date("2026-07-12"), audienceRoles: [UserGroup.LEAD_BSE, UserGroup.MANAGEMENT, UserGroup.ADMIN], readBy: [] as string[] },
  { id: "ntf-6", type: "Pending Validation", message: "5 submissions are awaiting manager validation for more than 5 days.", severity: Severity.MEDIUM, relatedId: null, date: new Date("2026-07-20"), audienceRoles: [UserGroup.LEAD_BSE], readBy: [] as string[] },
  { id: "ntf-7", type: "Low Team Adoption", message: "Presales - SME & Growth has the lowest AI adoption rate of all four teams this quarter.", severity: Severity.MEDIUM, relatedId: "team-ps-sme", date: new Date("2026-07-15"), audienceRoles: [UserGroup.LEAD_BSE, UserGroup.MANAGEMENT], readBy: [] as string[] },
  { id: "ntf-8", type: "Subscription Underutilization", message: "GitHub Copilot has 10 seats provisioned but only 3 active users in the last 30 days.", severity: Severity.LOW, relatedId: "tool-ghcopilot", date: new Date("2026-07-18"), audienceRoles: [UserGroup.ADMIN, UserGroup.MANAGEMENT], readBy: [] as string[] },
  { id: "ntf-9", type: "Prompt Due for Review", message: "CRD Section Drafting Template is due for its quarterly review following repeated accuracy flags.", severity: Severity.MEDIUM, relatedId: "rp-crd-outline", date: new Date("2026-07-12"), audienceRoles: [UserGroup.ADMIN], readBy: [] as string[] },
  { id: "ntf-10", type: "Sensitive Data Alert", message: "A Restricted-classification proposal draft was briefly opened in Gemini (not approved for Restricted data) before being moved to the internal assistant. Flagged for governance review.", severity: Severity.HIGH, relatedId: null, date: new Date("2026-04-09"), audienceRoles: [UserGroup.ADMIN, UserGroup.MANAGEMENT], readBy: [] as string[] },
  { id: "ntf-11", type: "Data Quality", message: "3 submissions this quarter are missing an evidence attachment despite a non-zero claimed benefit.", severity: Severity.MEDIUM, relatedId: null, date: new Date("2026-07-20"), audienceRoles: [UserGroup.ADMIN, UserGroup.LEAD_BSE], readBy: [] as string[] },
  { id: "ntf-12", type: "Inactive User", message: "Employee EMP-112 (Chamodi Rathnayake) has not logged an AI-assisted activity in over 3 weeks despite active AI tool access.", severity: Severity.LOW, relatedId: "emp-112", date: new Date("2026-07-20"), audienceRoles: [UserGroup.LEAD_BSE], readBy: [] as string[] },
];
