import {
  CollaborationType,
  FinalOutcome,
  ValidationStatus,
  ReusabilityLevel,
  ConfidentialityClassification,
} from "../../generated/prisma/client";

export const optimizationSubmissions = [
  {
    id: "OPT-2001", employeeId: "emp-101", submissionDate: new Date("2026-02-10"), activityDate: new Date("2026-02-10"),
    projectId: "proj-1", activityCategoryId: "ba-mom", activitySubcategory: "Client meeting recap",
    taskDescription: "Prepare Minutes of Meeting for the Core Banking Phase 2 requirements walkthrough with Meridian National Bank.",
    aiToolId: "tool-internal", aiModel: "hSenid-LLM v2", promptOrWorkflow: "Fed the meeting recording + agenda into the internal assistant using the \"Meeting-to-MoM Recap\" prompt, then reordered by agenda item.",
    reusablePromptUsed: true, reusablePromptId: "rp-mom-recap", collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Structured MoM draft with action items grouped by owner.", finalOutputSummary: "MoM circulated to client within the hour, 2 action-item owners corrected.",
    estEffortWithoutAI: 1.5, actualEffortWithAI: 0.58, reviewCorrectionTime: 0.17, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 1, defectsAfter: 0, reworkTimeAvoided: 0.9,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Recorded task start and completion times", evidenceFileName: "mom-timestamps-proj1-feb10.png", supportingLink: "https://internal.crm/meetings/8841",
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-201", validatedDate: new Date("2026-02-11"), managerComments: "Matches meeting recording timestamps. Good template use.",
    reusabilityLevel: ReusabilityLevel.TEAM, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    coeSessionId: "coe-mom-ai-capture",
    flags: [] as string[],
  },
  {
    id: "OPT-2002", employeeId: "emp-102", submissionDate: new Date("2026-02-18"), activityDate: new Date("2026-02-17"),
    projectId: "proj-1", activityCategoryId: "ba-crd", activitySubcategory: "Fee schedule change request",
    taskDescription: "Draft the impact section of a Change Request Document for a new fee schedule module.",
    aiToolId: "tool-chatgpt", aiModel: "GPT-4o", promptOrWorkflow: "Used the CRD Section Drafting Template with the existing BRD as context.",
    reusablePromptUsed: true, reusablePromptId: "rp-crd-outline", collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Drafted impact, assumptions and rollback sections.", finalOutputSummary: "Impact section required 3 factual corrections - AI referenced a deprecated fee cap that no longer applies.",
    estEffortWithoutAI: 5, actualEffortWithAI: 3, reviewCorrectionTime: 0.75, iterations: 2,
    qualityBefore: 3, qualityAfter: 3, defectsBefore: 2, defectsAfter: 3, reworkTimeAvoided: -0.75,
    finalOutcome: FinalOutcome.ADOPTED_WITH_EDITS, evidenceType: "Document revision history", evidenceFileName: "crd-fee-schedule-v3-diff.pdf", supportingLink: "https://internal.pm/proj-1/docs/crd-142",
    validationStatus: ValidationStatus.NEEDS_CLARIFICATION, validatedById: "mgr-201", validatedDate: new Date("2026-02-19"), managerComments: "Please confirm which fee cap version was used as source context before we validate the time saving.",
    reusabilityLevel: ReusabilityLevel.DEPARTMENT, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2003", employeeId: "emp-107", submissionDate: new Date("2026-03-05"), activityDate: new Date("2026-03-03"),
    projectId: "proj-3", activityCategoryId: "ps-rfp-response", activitySubcategory: "Technical + commercial response",
    taskDescription: "Prepare the full RFP response for PrimeTel Mobile 5G OSS/BSS integration, covering technical, commercial and compliance sections.",
    aiToolId: "tool-claude", aiModel: "Claude Sonnet 4.5", promptOrWorkflow: "Used the RFP Response Skeleton Workflow to generate section drafts, split across 3 contributors for domain review.",
    reusablePromptUsed: true, reusablePromptId: "rp-rfp-structure", collaborationType: CollaborationType.COLLABORATIVE, collaboratorsCount: 3,
    aiOutputSummary: "Full first-draft response across 9 RFP sections.", finalOutputSummary: "Submitted response, technical section rewritten lightly for OSS integration specifics.",
    estEffortWithoutAI: 24, actualEffortWithAI: 16, reviewCorrectionTime: 2, iterations: 3,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 4, defectsAfter: 1, reworkTimeAvoided: 6,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Proposal submission history", evidenceFileName: "rfp-primetel-submission-log.pdf", supportingLink: "https://internal.crm/opportunities/proj-3",
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-203", validatedDate: new Date("2026-03-07"), managerComments: "Strong team effort, RFP won. Time entries cross-checked against timesheets for all 3 contributors.",
    reusabilityLevel: ReusabilityLevel.ORG_WIDE, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    coeSessionId: "coe-rfp-skeleton",
    flags: [] as string[],
  },
  {
    id: "OPT-2004", employeeId: "emp-108", submissionDate: new Date("2026-03-12"), activityDate: new Date("2026-03-11"),
    projectId: "proj-6", activityCategoryId: "ps-presentation-prep", activitySubcategory: "Proposal deck",
    taskDescription: "Build the proposal presentation deck for Gulf Trust Bank corporate internet banking RFP.",
    aiToolId: "tool-gamma", aiModel: "Gamma Gen 2", promptOrWorkflow: "Generated deck structure and visuals from the approved proposal outline using Gamma.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "22-slide deck with speaker notes.", finalOutputSummary: "Brand template swapped in, 2 slides simplified for exec audience.",
    estEffortWithoutAI: 8, actualEffortWithAI: 4.5, reviewCorrectionTime: 0.5, iterations: 2,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 2, defectsAfter: 0, reworkTimeAvoided: 3,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Document timestamps", evidenceFileName: "gulf-trust-deck-v2-timestamps.png", supportingLink: "https://internal.crm/opportunities/proj-6",
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-203", validatedDate: new Date("2026-03-13"), managerComments: "Deal ultimately lost on price, but deck quality was not a factor per client feedback.",
    reusabilityLevel: ReusabilityLevel.TEAM, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2005", employeeId: "emp-111", submissionDate: new Date("2026-03-20"), activityDate: new Date("2026-03-19"),
    projectId: "proj-5", activityCategoryId: "ps-competitor-comparison", activitySubcategory: "Fintech wallet competitors",
    taskDescription: "Research competing digital wallet vendors active in East Africa for the MobiPay POC.",
    aiToolId: "tool-perplexity", aiModel: "Sonar Pro", promptOrWorkflow: "Used the Competitor Snapshot Prompt across 5 named competitors, cross-checked citations.",
    reusablePromptUsed: true, reusablePromptId: "rp-competitor-brief", collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Comparison table across 5 vendors with cited sources.", finalOutputSummary: "One vendor pricing figure was outdated and had to be manually re-verified against a 2026 source.",
    estEffortWithoutAI: 6, actualEffortWithAI: 3, reviewCorrectionTime: 0.75, iterations: 1,
    qualityBefore: 3, qualityAfter: 3, defectsBefore: 0, defectsAfter: 1, reworkTimeAvoided: 2.25,
    finalOutcome: FinalOutcome.ADOPTED_WITH_EDITS, evidenceType: "Screenshots or system-generated logs", evidenceFileName: "competitor-brief-sources.pdf", supportingLink: null,
    validationStatus: ValidationStatus.UNDER_REVIEW, validatedById: null, validatedDate: null, managerComments: null,
    reusabilityLevel: ReusabilityLevel.TEAM, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    coeSessionId: "coe-competitor-research-prompting",
    flags: [] as string[],
  },
  {
    id: "OPT-2006", employeeId: "emp-103", submissionDate: new Date("2026-01-22"), activityDate: new Date("2026-01-21"),
    projectId: "proj-1", activityCategoryId: "ba-test-scenario", activitySubcategory: "Fee schedule module",
    taskDescription: "Prepare test scenarios covering the new fee schedule module requirements.",
    aiToolId: "tool-chatgpt", aiModel: "GPT-4o", promptOrWorkflow: "Used the Test Scenario Generator prompt against the approved SRS section.",
    reusablePromptUsed: true, reusablePromptId: "rp-testscenario-gen", collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "18 test scenarios covering happy path and edge cases.", finalOutputSummary: "18 scenarios retained, 2 additional edge cases added manually.",
    estEffortWithoutAI: 4, actualEffortWithAI: 2.5, reviewCorrectionTime: 0.25, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 3, defectsAfter: 1, reworkTimeAvoided: 1.25,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Approved effort estimations", evidenceFileName: "test-scenarios-approved.xlsx", supportingLink: "https://internal.pm/proj-1/tasks/551",
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-201", validatedDate: new Date("2026-01-23"), managerComments: "Good coverage, consistent with historical scenario counts.",
    reusabilityLevel: ReusabilityLevel.DEPARTMENT, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2007", employeeId: "emp-104", submissionDate: new Date("2026-01-28"), activityDate: new Date("2026-01-28"),
    projectId: "proj-3", activityCategoryId: "ba-req-clarification", activitySubcategory: "OSS integration questions",
    taskDescription: "Draft clarification questions to send to PrimeTel Mobile on OSS integration requirements ambiguities.",
    aiToolId: "tool-claude", aiModel: "Claude Sonnet 4.5", promptOrWorkflow: "Summarized ambiguous requirement clauses and generated a prioritized question list.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "11 clarification questions grouped by requirement area.", finalOutputSummary: "9 questions sent as-is, 2 merged.",
    estEffortWithoutAI: 2, actualEffortWithAI: 0.75, reviewCorrectionTime: 0.08, iterations: 1,
    qualityBefore: 4, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 1.17,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Email timestamps", evidenceFileName: "clarification-email-sent.png", supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-202", validatedDate: new Date("2026-01-29"), managerComments: "Clean, well-prioritized list.",
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2008", employeeId: "emp-106", submissionDate: new Date("2026-02-02"), activityDate: new Date("2026-02-01"),
    projectId: "proj-3", activityCategoryId: "ba-diagram", activitySubcategory: "Provisioning flow",
    taskDescription: "Create the process flow diagram for the OSS subscriber provisioning workflow.",
    aiToolId: "tool-whimsical", aiModel: "Whimsical AI Diagrams", promptOrWorkflow: "Used the Process Flow Diagram Prompt describing the provisioning steps in text, generated the flowchart.",
    reusablePromptUsed: true, reusablePromptId: "rp-diagram-flow", collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Flowchart with 14 nodes and 3 decision branches.", finalOutputSummary: "One missing error-handling branch added manually.",
    estEffortWithoutAI: 3, actualEffortWithAI: 1.5, reviewCorrectionTime: 0.25, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 1, defectsAfter: 0, reworkTimeAvoided: 1.25,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Document revision history", evidenceFileName: "provisioning-flow-v2.pdf", supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-202", validatedDate: new Date("2026-02-03"), managerComments: "Matches the SRS provisioning section.",
    reusabilityLevel: ReusabilityLevel.TEAM, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2009", employeeId: "emp-101", submissionDate: new Date("2026-02-25"), activityDate: new Date("2026-02-24"),
    projectId: "proj-1", activityCategoryId: "ba-doc-review", activitySubcategory: "BRD review pass",
    taskDescription: "AI-assisted review of the Core Banking Phase 2 BRD prior to customer sign-off.",
    aiToolId: "tool-chatgpt", aiModel: "GPT-4o", promptOrWorkflow: "Ran a structured completeness and consistency check against the requirement template checklist.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Flagged 12 potential issues: missing NFRs, inconsistent terminology, unresolved TBDs.", finalOutputSummary: "9 of 12 flagged issues confirmed valid and corrected before sign-off; 3 were false positives.",
    estEffortWithoutAI: 2, actualEffortWithAI: 1.25, reviewCorrectionTime: 0.5, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 5, defectsAfter: 1, reworkTimeAvoided: 0.25,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Internal review comments", evidenceFileName: "brd-review-findings.xlsx", supportingLink: "https://internal.pm/proj-1/docs/brd-review-9",
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-201", validatedDate: new Date("2026-02-26"), managerComments: "9 of 12 AI-flagged issues verified by me directly against the BRD - good defect-detection value.",
    reusabilityLevel: ReusabilityLevel.DEPARTMENT, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2010", employeeId: "emp-109", submissionDate: new Date("2026-04-08"), activityDate: new Date("2026-04-07"),
    projectId: "proj-6", activityCategoryId: "ps-solution-description", activitySubcategory: "Core banking module description",
    taskDescription: "Draft the solution description section explaining the core banking integration approach for Gulf Trust Bank.",
    aiToolId: "tool-gemini", aiModel: "Gemini 2.5 Pro", promptOrWorkflow: "Generated the technical solution narrative directly from the architecture diagram without domain fact-checking prompts.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Solution narrative describing integration approach and APIs used.", finalOutputSummary: "Discarded after review - referenced an API version we do not support and invented a caching layer that does not exist. Rewritten manually.",
    estEffortWithoutAI: 4, actualEffortWithAI: 3, reviewCorrectionTime: 2.5, iterations: 3,
    qualityBefore: 3, qualityAfter: 2, defectsBefore: 1, defectsAfter: 4, reworkTimeAvoided: -1.5,
    finalOutcome: FinalOutcome.DISCARDED, evidenceType: "Document revision history", evidenceFileName: "solution-desc-discarded-v1.pdf", supportingLink: null,
    validationStatus: ValidationStatus.REJECTED, validatedById: "mgr-203", validatedDate: new Date("2026-04-09"), managerComments: "Claimed time saving not accepted - the output introduced factual errors that cost more time to unwind than writing it manually would have. Flagging Gemini for solution-description work until prompt guardrails improve.",
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2011", employeeId: "emp-105", submissionDate: new Date("2026-01-15"), activityDate: new Date("2026-01-14"),
    projectId: "proj-3", activityCategoryId: "ba-srs", activitySubcategory: "OSS integration SRS",
    taskDescription: "Draft the Software Requirement Specification for the OSS/BSS integration module.",
    aiToolId: "tool-chatgpt", aiModel: "GPT-4o", promptOrWorkflow: "Converted approved requirement notes into structured SRS sections with numbering.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Full SRS draft with functional and non-functional sections.", finalOutputSummary: "Reviewed and approved with minor renumbering.",
    estEffortWithoutAI: 12, actualEffortWithAI: 8, reviewCorrectionTime: 1, iterations: 2,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 3, defectsAfter: 1, reworkTimeAvoided: 3,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Timesheet entries", evidenceFileName: "srs-timesheet-jan.xlsx", supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-202", validatedDate: new Date("2026-01-16"), managerComments: "Consistent with timesheet log.",
    reusabilityLevel: ReusabilityLevel.TEAM, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2012", employeeId: "emp-101", submissionDate: new Date("2026-04-02"), activityDate: new Date("2026-04-01"),
    projectId: "proj-9", activityCategoryId: "ba-brd", activitySubcategory: "Merchant gateway BRD",
    taskDescription: "Draft the Business Requirement Document for the merchant payment gateway integration.",
    aiToolId: "tool-claude", aiModel: "Claude Sonnet 4.5", promptOrWorkflow: "Generated BRD sections from stakeholder workshop notes, iterated twice for structure.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Full BRD draft including scope, stakeholders, and functional requirements.", finalOutputSummary: "Approved with 1 hour of stakeholder-name corrections.",
    estEffortWithoutAI: 10, actualEffortWithAI: 6.5, reviewCorrectionTime: 1, iterations: 2,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 2, defectsAfter: 0, reworkTimeAvoided: 2.5,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Previous versions of similar documents", evidenceFileName: "brd-merchant-gateway-v2.pdf", supportingLink: "https://internal.pm/proj-9/docs/brd-1",
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-201", validatedDate: new Date("2026-04-03"), managerComments: "Solid draft, on par with our best historical BRDs.",
    reusabilityLevel: ReusabilityLevel.TEAM, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2013", employeeId: "emp-102", submissionDate: new Date("2026-04-10"), activityDate: new Date("2026-04-09"),
    projectId: "proj-9", activityCategoryId: "ba-usecase", activitySubcategory: "Merchant onboarding use cases",
    taskDescription: "Create use cases for merchant onboarding and settlement flows.",
    aiToolId: "tool-chatgpt", aiModel: "GPT-4o", promptOrWorkflow: "Generated use cases from the BRD scope section, one prompt per actor.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "8 use cases covering 3 actor types.", finalOutputSummary: "All 8 retained with minor wording edits.",
    estEffortWithoutAI: 3, actualEffortWithAI: 1.5, reviewCorrectionTime: 0.25, iterations: 1,
    qualityBefore: 4, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 1.25,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Timesheet entries", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.SUBMITTED, validatedById: null, validatedDate: null, managerComments: null,
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2014", employeeId: "emp-103", submissionDate: new Date("2026-04-15"), activityDate: new Date("2026-04-14"),
    projectId: "proj-1", activityCategoryId: "ba-userstory", activitySubcategory: "Fee schedule stories",
    taskDescription: "Write user stories for the fee schedule configuration screens.",
    aiToolId: "tool-claude", aiModel: "Claude Sonnet 4.5", promptOrWorkflow: "Generated user stories with acceptance notes from the wireframes.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "10 user stories with INVEST-format acceptance notes.", finalOutputSummary: "All 10 accepted with light rewording.",
    estEffortWithoutAI: 2.5, actualEffortWithAI: 1.25, reviewCorrectionTime: 0.25, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 1, defectsAfter: 0, reworkTimeAvoided: 1,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Approved effort estimations", evidenceFileName: "userstories-fee-schedule.xlsx", supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-201", validatedDate: new Date("2026-04-16"), managerComments: "Good acceptance-note quality.",
    reusabilityLevel: ReusabilityLevel.TEAM, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2015", employeeId: "emp-104", submissionDate: new Date("2026-04-20"), activityDate: new Date("2026-04-19"),
    projectId: "proj-10", activityCategoryId: "ba-acceptance-criteria", activitySubcategory: "Digital lending criteria",
    taskDescription: "Prepare acceptance criteria for the SME digital lending eligibility engine.",
    aiToolId: "tool-chatgpt", aiModel: "GPT-4o", promptOrWorkflow: "Generated Given-When-Then acceptance criteria from the eligibility rules document.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "15 Given-When-Then criteria.", finalOutputSummary: "14 retained, 1 duplicate removed.",
    estEffortWithoutAI: 2, actualEffortWithAI: 1, reviewCorrectionTime: 0.17, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 1, defectsAfter: 0, reworkTimeAvoided: 0.83,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Timesheet entries", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-202", validatedDate: new Date("2026-04-21"), managerComments: "Clean and consistent format.",
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2016", employeeId: "emp-106", submissionDate: new Date("2026-05-02"), activityDate: new Date("2026-05-01"),
    projectId: "proj-10", activityCategoryId: "ba-api-req-analysis", activitySubcategory: "Lending API requirements",
    taskDescription: "Analyze API requirements for the credit bureau integration in the digital lending engine.",
    aiToolId: "tool-claude", aiModel: "Claude Sonnet 4.5", promptOrWorkflow: "Reviewed vendor API docs and generated an internal requirements summary with gaps flagged.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Requirements summary with 3 flagged ambiguities.", finalOutputSummary: "Ambiguities resolved with vendor, 1 endpoint mapping corrected.",
    estEffortWithoutAI: 4, actualEffortWithAI: 2.5, reviewCorrectionTime: 0.5, iterations: 1,
    qualityBefore: 3, qualityAfter: 3, defectsBefore: 1, defectsAfter: 1, reworkTimeAvoided: 1,
    finalOutcome: FinalOutcome.ADOPTED_WITH_EDITS, evidenceType: "Document revision history", evidenceFileName: "lending-api-req-v2.pdf", supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-202", validatedDate: new Date("2026-05-03"), managerComments: "Reasonable, one endpoint still needed manual correction.",
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2017", employeeId: "emp-105", submissionDate: new Date("2026-05-06"), activityDate: new Date("2026-05-05"),
    projectId: "proj-3", activityCategoryId: "ba-api-documentation", activitySubcategory: "Provisioning API docs",
    taskDescription: "Document the subscriber provisioning API endpoints for the OSS integration.",
    aiToolId: "tool-ghcopilot", aiModel: "Copilot Codex", promptOrWorkflow: "Generated OpenAPI-style documentation from the endpoint definitions and sample payloads.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Documentation for 9 endpoints with request/response examples.", finalOutputSummary: "Approved with 2 example payloads corrected.",
    estEffortWithoutAI: 5, actualEffortWithAI: 3, reviewCorrectionTime: 0.5, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 2, defectsAfter: 0, reworkTimeAvoided: 1.5,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Document revision history", evidenceFileName: "provisioning-api-docs-v2.pdf", supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-202", validatedDate: new Date("2026-05-07"), managerComments: "Good structure, examples now accurate.",
    reusabilityLevel: ReusabilityLevel.TEAM, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2018", employeeId: "emp-101", submissionDate: new Date("2026-05-10"), activityDate: new Date("2026-05-09"),
    projectId: "proj-1", activityCategoryId: "ba-gap-analysis", activitySubcategory: "Fee schedule vs legacy system",
    taskDescription: "Perform gap analysis between the new fee schedule module and the legacy billing system.",
    aiToolId: "tool-chatgpt", aiModel: "GPT-4o", promptOrWorkflow: "Compared legacy field mapping doc against new schema, generated a gap list.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "13 gaps identified across data mapping and business rules.", finalOutputSummary: "11 confirmed as real gaps, 2 already handled.",
    estEffortWithoutAI: 6, actualEffortWithAI: 4.5, reviewCorrectionTime: 0.75, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 2, defectsAfter: 1, reworkTimeAvoided: 0.75,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Gap analysis records", evidenceFileName: "gap-analysis-fee-schedule.xlsx", supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-201", validatedDate: new Date("2026-05-11"), managerComments: "Thorough, verified 11 of 13 personally.",
    reusabilityLevel: ReusabilityLevel.TEAM, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2019", employeeId: "emp-102", submissionDate: new Date("2026-05-14"), activityDate: new Date("2026-05-13"),
    projectId: "proj-9", activityCategoryId: "ba-impact-analysis", activitySubcategory: "Merchant gateway rollout impact",
    taskDescription: "Assess downstream impact of the merchant gateway rollout on settlement reconciliation.",
    aiToolId: "tool-claude", aiModel: "Claude Sonnet 4.5", promptOrWorkflow: "Generated an impact matrix across affected systems from the integration design doc.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Impact matrix across 6 downstream systems.", finalOutputSummary: "Under review by reconciliation team lead.",
    estEffortWithoutAI: 4, actualEffortWithAI: 2.75, reviewCorrectionTime: 0.5, iterations: 1,
    qualityBefore: 3, qualityAfter: 3, defectsBefore: 1, defectsAfter: 1, reworkTimeAvoided: 0.75,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Impact analysis records", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.UNDER_REVIEW, validatedById: null, validatedDate: null, managerComments: null,
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2020", employeeId: "emp-103", submissionDate: new Date("2026-05-18"), activityDate: new Date("2026-05-17"),
    projectId: "proj-1", activityCategoryId: "ba-root-cause", activitySubcategory: "Reconciliation mismatch",
    taskDescription: "Root-cause a recurring reconciliation mismatch reported during UAT.",
    aiToolId: "tool-chatgpt", aiModel: "GPT-4o", promptOrWorkflow: "Fed the defect log and reconciliation rules into the model to narrow down candidate causes.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Narrowed 5 candidate causes to 1 most likely - a rounding rule mismatch.", finalOutputSummary: "Confirmed correct on investigation, fix deployed.",
    estEffortWithoutAI: 3, actualEffortWithAI: 2, reviewCorrectionTime: 0.25, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 1, defectsAfter: 0, reworkTimeAvoided: 0.75,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Error or defect records", evidenceFileName: "defect-log-rc-118.pdf", supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-201", validatedDate: new Date("2026-05-19"), managerComments: "Correct root cause identified quickly.",
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2021", employeeId: "emp-104", submissionDate: new Date("2026-05-22"), activityDate: new Date("2026-05-21"),
    projectId: "proj-10", activityCategoryId: "ba-mom", activitySubcategory: "Lending workshop recap",
    taskDescription: "Prepare MoM for the SME digital lending requirements workshop with Union Microfinance Bank.",
    aiToolId: "tool-otter", aiModel: "Otter Transcribe v3", promptOrWorkflow: "Transcribed via Otter, summarized via the internal assistant using the Meeting-to-MoM Recap prompt.",
    reusablePromptUsed: true, reusablePromptId: "rp-mom-recap", collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Structured MoM with decisions and open items.", finalOutputSummary: "Circulated with no corrections needed.",
    estEffortWithoutAI: 1, actualEffortWithAI: 0.42, reviewCorrectionTime: 0.08, iterations: 1,
    qualityBefore: 4, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 0.5,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Recorded task start and completion times", evidenceFileName: "mom-lending-workshop.png", supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-202", validatedDate: new Date("2026-05-22"), managerComments: "Fast turnaround, well captured.",
    reusabilityLevel: ReusabilityLevel.TEAM, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2022", employeeId: "emp-106", submissionDate: new Date("2026-05-25"), activityDate: new Date("2026-05-24"),
    projectId: "proj-10", activityCategoryId: "ba-report-analysis", activitySubcategory: "Loan default trend report",
    taskDescription: "Analyze the quarterly loan default trend report to extract requirement implications for the eligibility engine.",
    aiToolId: "tool-chatgpt", aiModel: "GPT-4o", promptOrWorkflow: "Summarized key trend drivers and mapped them to eligibility rule changes.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Summary with 4 rule-change recommendations.", finalOutputSummary: "3 recommendations adopted, 1 deferred.",
    estEffortWithoutAI: 3, actualEffortWithAI: 2, reviewCorrectionTime: 0.25, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 0.75,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Report analysis records", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-202", validatedDate: new Date("2026-05-26"), managerComments: "Good synthesis of trend data.",
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2023", employeeId: "emp-105", submissionDate: new Date("2026-06-01"), activityDate: new Date("2026-05-31"),
    projectId: "proj-3", activityCategoryId: "ba-data-analysis", activitySubcategory: "Network usage patterns",
    taskDescription: "Analyze sample network usage data to validate OSS provisioning assumptions.",
    aiToolId: "tool-gemini", aiModel: "Gemini 2.5 Pro", promptOrWorkflow: "Uploaded anonymized usage dataset for pattern summarization and anomaly flagging.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Summary of usage patterns with 2 anomalies flagged.", finalOutputSummary: "Both anomalies confirmed as data entry errors, excluded from analysis.",
    estEffortWithoutAI: 4, actualEffortWithAI: 2.5, reviewCorrectionTime: 0.5, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 1,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Data analysis records", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-202", validatedDate: new Date("2026-06-02"), managerComments: "Anomaly detection was genuinely useful here.",
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2024", employeeId: "emp-101", submissionDate: new Date("2026-06-05"), activityDate: new Date("2026-06-04"),
    projectId: "proj-1", activityCategoryId: "ba-translation", activitySubcategory: "Sinhala customer notice",
    taskDescription: "Translate the fee schedule customer notice into Sinhala for local branch rollout.",
    aiToolId: "tool-chatgpt", aiModel: "GPT-4o", promptOrWorkflow: "Translated and then reviewed for banking terminology accuracy.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Full Sinhala translation of the customer notice.", finalOutputSummary: "Two banking terms adjusted for regulatory phrasing.",
    estEffortWithoutAI: 2, actualEffortWithAI: 0.75, reviewCorrectionTime: 0.17, iterations: 1,
    qualityBefore: 4, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 1.08,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Document timestamps", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-201", validatedDate: new Date("2026-06-06"), managerComments: "Terminology now correct.",
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.PUBLIC,
    flags: [] as string[],
  },
  {
    id: "OPT-2025", employeeId: "emp-102", submissionDate: new Date("2026-06-08"), activityDate: new Date("2026-06-07"),
    projectId: "proj-9", activityCategoryId: "ba-audit-prep", activitySubcategory: "PCI-DSS evidence pack",
    taskDescription: "Prepare the audit evidence pack for the merchant gateway PCI-DSS review.",
    aiToolId: "tool-claude", aiModel: "Claude Sonnet 4.5", promptOrWorkflow: "Compiled and cross-referenced control evidence against the PCI-DSS checklist.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Evidence pack mapped to 12 PCI-DSS controls.", finalOutputSummary: "Submitted for internal audit review.",
    estEffortWithoutAI: 5, actualEffortWithAI: 3.5, reviewCorrectionTime: 0.5, iterations: 1,
    qualityBefore: 3, qualityAfter: 3, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 1,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Audit preparation records", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.SUBMITTED, validatedById: null, validatedDate: null, managerComments: null,
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.RESTRICTED,
    flags: [] as string[],
  },
  {
    id: "OPT-2026", employeeId: "emp-103", submissionDate: new Date("2026-06-12"), activityDate: new Date("2026-06-11"),
    projectId: "proj-1", activityCategoryId: "ba-compliance-doc", activitySubcategory: "Data residency compliance note",
    taskDescription: "Prepare a compliance note on data residency requirements for the fee schedule module.",
    aiToolId: "tool-chatgpt", aiModel: "GPT-4o", promptOrWorkflow: "Summarized applicable regulations and mapped them to current architecture.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Compliance note covering 3 applicable regulations.", finalOutputSummary: "Legal team confirmed accuracy with 1 clause reworded.",
    estEffortWithoutAI: 6, actualEffortWithAI: 4, reviewCorrectionTime: 0.75, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 1, defectsAfter: 0, reworkTimeAvoided: 1.25,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Internal review comments", evidenceFileName: "compliance-note-legal-review.pdf", supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-201", validatedDate: new Date("2026-06-13"), managerComments: "Confirmed by legal.",
    reusabilityLevel: ReusabilityLevel.TEAM, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2027", employeeId: "emp-104", submissionDate: new Date("2026-06-15"), activityDate: new Date("2026-06-14"),
    projectId: "proj-3", activityCategoryId: "ba-research-competitor", activitySubcategory: "OSS vendor landscape",
    taskDescription: "Research the competitive OSS/BSS vendor landscape relevant to the PrimeTel deal.",
    aiToolId: "tool-perplexity", aiModel: "Sonar Pro", promptOrWorkflow: "Compiled vendor landscape summary with citations for internal briefing.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Landscape summary across 6 vendors.", finalOutputSummary: "Used directly in internal deal briefing.",
    estEffortWithoutAI: 5, actualEffortWithAI: 3, reviewCorrectionTime: 0.5, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 1.5,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Research and competitor analysis records", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-202", validatedDate: new Date("2026-06-16"), managerComments: "Well cited, used as-is.",
    reusabilityLevel: ReusabilityLevel.TEAM, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2028", employeeId: "emp-107", submissionDate: new Date("2026-04-25"), activityDate: new Date("2026-04-24"),
    projectId: "proj-6", activityCategoryId: "ps-solution-design", activitySubcategory: "Core banking integration architecture",
    taskDescription: "Design the technical solution architecture for the Gulf Trust Bank corporate internet banking RFP.",
    aiToolId: "tool-claude", aiModel: "Claude Sonnet 4.5", promptOrWorkflow: "Generated candidate architecture options from requirements, refined with the solutions team.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Architecture diagram and narrative with 2 integration options.", finalOutputSummary: "Option 2 selected and refined for the final proposal.",
    estEffortWithoutAI: 10, actualEffortWithAI: 7, reviewCorrectionTime: 1, iterations: 2,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 1, defectsAfter: 0, reworkTimeAvoided: 2,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Approved effort estimations", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-203", validatedDate: new Date("2026-04-26"), managerComments: "Solid architecture options.",
    reusabilityLevel: ReusabilityLevel.TEAM, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2029", employeeId: "emp-108", submissionDate: new Date("2026-05-01"), activityDate: new Date("2026-04-30"),
    projectId: "proj-6", activityCategoryId: "ps-scope-definition", activitySubcategory: "RFP scope boundaries",
    taskDescription: "Define in-scope and out-of-scope boundaries for the corporate internet banking proposal.",
    aiToolId: "tool-chatgpt", aiModel: "GPT-4o", promptOrWorkflow: "Generated scope boundary draft from the RFP requirements list.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Scope draft with 14 in-scope and 6 out-of-scope items.", finalOutputSummary: "Approved with 1 item moved to out-of-scope.",
    estEffortWithoutAI: 4, actualEffortWithAI: 2.5, reviewCorrectionTime: 0.5, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 1,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Project-management records", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-203", validatedDate: new Date("2026-05-02"), managerComments: "Clear boundaries.",
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2030", employeeId: "emp-109", submissionDate: new Date("2026-05-05"), activityDate: new Date("2026-05-04"),
    projectId: "proj-6", activityCategoryId: "ps-assumption-dependency", activitySubcategory: "Integration assumptions",
    taskDescription: "Prepare the assumptions and dependencies section for the internet banking proposal.",
    aiToolId: "tool-claude", aiModel: "Claude Sonnet 4.5", promptOrWorkflow: "Generated assumptions list from the solution design and scope documents.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "9 assumptions and 5 dependencies listed.", finalOutputSummary: "Approved as-is.",
    estEffortWithoutAI: 2, actualEffortWithAI: 1, reviewCorrectionTime: 0.25, iterations: 1,
    qualityBefore: 4, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 0.75,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Project-management records", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-203", validatedDate: new Date("2026-05-06"), managerComments: "No issues.",
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2031", employeeId: "emp-110", submissionDate: new Date("2026-05-08"), activityDate: new Date("2026-05-07"),
    projectId: "proj-5", activityCategoryId: "ps-effort-estimation", activitySubcategory: "POC effort estimate",
    taskDescription: "Support effort estimation for the MobiPay digital wallet POC.",
    aiToolId: "tool-chatgpt", aiModel: "GPT-4o", promptOrWorkflow: "Generated a first-pass effort breakdown by workstream for review against team benchmarks.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Effort breakdown across 5 workstreams.", finalOutputSummary: "2 workstreams re-estimated upward after team review.",
    estEffortWithoutAI: 3, actualEffortWithAI: 2, reviewCorrectionTime: 0.5, iterations: 1,
    qualityBefore: 3, qualityAfter: 3, defectsBefore: 1, defectsAfter: 1, reworkTimeAvoided: 0.5,
    finalOutcome: FinalOutcome.ADOPTED_WITH_EDITS, evidenceType: "Approved effort estimations", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.UNDER_REVIEW, validatedById: null, validatedDate: null, managerComments: null,
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2032", employeeId: "emp-111", submissionDate: new Date("2026-05-12"), activityDate: new Date("2026-05-11"),
    projectId: "proj-5", activityCategoryId: "ps-commercial-proposal", activitySubcategory: "POC commercial terms",
    taskDescription: "Draft the commercial proposal section for the MobiPay POC engagement.",
    aiToolId: "tool-claude", aiModel: "Claude Sonnet 4.5", promptOrWorkflow: "Generated commercial terms narrative from the approved pricing model.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Commercial section with pricing table and payment terms.", finalOutputSummary: "Approved with currency formatting corrected.",
    estEffortWithoutAI: 6, actualEffortWithAI: 4, reviewCorrectionTime: 0.75, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 1, defectsAfter: 0, reworkTimeAvoided: 1.25,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Approved estimation", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-204", validatedDate: new Date("2026-05-13"), managerComments: "Pricing table matched approved model.",
    reusabilityLevel: ReusabilityLevel.TEAM, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2033", employeeId: "emp-112", submissionDate: new Date("2026-05-15"), activityDate: new Date("2026-05-14"),
    projectId: "proj-5", activityCategoryId: "ps-demo-prep", activitySubcategory: "Wallet demo walkthrough",
    taskDescription: "Prepare the demo script and walkthrough flow for the MobiPay wallet POC demo.",
    aiToolId: "tool-gamma", aiModel: "Gamma Gen 2", promptOrWorkflow: "Used the Demo Script & Data Builder workflow to generate the walkthrough script and sample screens.",
    reusablePromptUsed: true, reusablePromptId: "rp-demo-script", collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Demo script with 8 walkthrough steps.", finalOutputSummary: "Approved with 1 step reordered for narrative flow.",
    estEffortWithoutAI: 5, actualEffortWithAI: 3, reviewCorrectionTime: 0.5, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 1.5,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Meeting preparation duration", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-204", validatedDate: new Date("2026-05-16"), managerComments: "Smooth narrative flow.",
    reusabilityLevel: ReusabilityLevel.TEAM, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2034", employeeId: "emp-107", submissionDate: new Date("2026-05-20"), activityDate: new Date("2026-05-19"),
    projectId: "proj-8", activityCategoryId: "ps-demo-data-gen", activitySubcategory: "Unified comms demo data",
    taskDescription: "Generate realistic demo data for the unified communications proposal demo.",
    aiToolId: "tool-chatgpt", aiModel: "GPT-4o", promptOrWorkflow: "Generated synthetic call-log and usage data sets matching the client industry profile.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Synthetic dataset of 500 sample records.", finalOutputSummary: "Used directly, no corrections.",
    estEffortWithoutAI: 3, actualEffortWithAI: 1.5, reviewCorrectionTime: 0.25, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 1.25,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Screenshots or system-generated logs", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-203", validatedDate: new Date("2026-05-21"), managerComments: "Realistic and industry-appropriate.",
    reusabilityLevel: ReusabilityLevel.TEAM, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2035", employeeId: "emp-108", submissionDate: new Date("2026-05-24"), activityDate: new Date("2026-05-23"),
    projectId: "proj-8", activityCategoryId: "ps-customer-usecase", activitySubcategory: "Enterprise comms use cases",
    taskDescription: "Identify relevant customer use cases for the unified comms proposal based on the client industry.",
    aiToolId: "tool-claude", aiModel: "Claude Sonnet 4.5", promptOrWorkflow: "Generated candidate use cases matched to the client sector and company size.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "6 candidate use cases with relevance scoring.", finalOutputSummary: "4 selected for the proposal.",
    estEffortWithoutAI: 2, actualEffortWithAI: 1, reviewCorrectionTime: 0.17, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 0.83,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Customer feedback", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-203", validatedDate: new Date("2026-05-25"), managerComments: "Relevant selections.",
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2036", employeeId: "emp-110", submissionDate: new Date("2026-05-28"), activityDate: new Date("2026-05-27"),
    projectId: "proj-5", activityCategoryId: "ps-market-research", activitySubcategory: "East Africa fintech market",
    taskDescription: "Research the East African mobile wallet market sizing and growth trends for the MobiPay deal brief.",
    aiToolId: "tool-perplexity", aiModel: "Sonar Pro", promptOrWorkflow: "Compiled market sizing figures with cited sources for the internal deal brief.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Market brief with sizing and 3-year growth trend.", finalOutputSummary: "Used directly in the deal brief.",
    estEffortWithoutAI: 5, actualEffortWithAI: 3, reviewCorrectionTime: 0.4, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 1.6,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "CRM records", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-204", validatedDate: new Date("2026-05-29"), managerComments: "Well sourced.",
    reusabilityLevel: ReusabilityLevel.TEAM, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2037", employeeId: "emp-111", submissionDate: new Date("2026-06-01"), activityDate: new Date("2026-05-31"),
    projectId: "proj-5", activityCategoryId: "ps-product-positioning", activitySubcategory: "Wallet positioning vs incumbents",
    taskDescription: "Prepare product positioning narrative against incumbent wallet providers.",
    aiToolId: "tool-chatgpt", aiModel: "GPT-4o", promptOrWorkflow: "Generated positioning statements based on the competitor comparison brief.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Positioning narrative with 3 differentiation pillars.", finalOutputSummary: "Approved, 1 pillar reworded for tone.",
    estEffortWithoutAI: 3, actualEffortWithAI: 2, reviewCorrectionTime: 0.25, iterations: 1,
    qualityBefore: 3, qualityAfter: 3, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 0.75,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Internal review comments", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-204", validatedDate: new Date("2026-06-02"), managerComments: "Fine as a first draft.",
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2038", employeeId: "emp-109", submissionDate: new Date("2026-06-04"), activityDate: new Date("2026-06-03"),
    projectId: "proj-6", activityCategoryId: "ps-technical-clarification", activitySubcategory: "API auth clarification",
    taskDescription: "Draft a technical clarification response to the client on API authentication approach.",
    aiToolId: "tool-claude", aiModel: "Claude Sonnet 4.5", promptOrWorkflow: "Generated the technical explanation from the architecture doc for a non-technical client contact.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Plain-language explanation of OAuth2 flow.", finalOutputSummary: "Sent as-is.",
    estEffortWithoutAI: 1.5, actualEffortWithAI: 0.75, reviewCorrectionTime: 0.1, iterations: 1,
    qualityBefore: 4, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 0.65,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Email timestamps", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-203", validatedDate: new Date("2026-06-05"), managerComments: "Clear explanation.",
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2039", employeeId: "emp-112", submissionDate: new Date("2026-06-08"), activityDate: new Date("2026-06-06"),
    projectId: "proj-10", activityCategoryId: "ps-tender-response", activitySubcategory: "Lending RFI response",
    taskDescription: "Prepare the tender response draft for the SME digital lending RFI.",
    aiToolId: "tool-chatgpt", aiModel: "GPT-4o", promptOrWorkflow: "Generated the first-draft response across all RFI sections.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Draft response across 7 RFI sections.", finalOutputSummary: "Submitted with 1 hour of pricing-table review.",
    estEffortWithoutAI: 8, actualEffortWithAI: 5.5, reviewCorrectionTime: 1, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 1, defectsAfter: 0, reworkTimeAvoided: 1.5,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Proposal submission history", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.SUBMITTED, validatedById: null, validatedDate: null, managerComments: null,
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2040", employeeId: "emp-107", submissionDate: new Date("2026-06-10"), activityDate: new Date("2026-06-09"),
    projectId: "proj-8", activityCategoryId: "ps-exec-summary", activitySubcategory: "Unified comms exec summary",
    taskDescription: "Prepare the executive summary for the unified communications proposal.",
    aiToolId: "tool-claude", aiModel: "Claude Sonnet 4.5", promptOrWorkflow: "Used the Executive Summary Generator prompt against the full proposal draft.",
    reusablePromptUsed: true, reusablePromptId: "rp-execsummary", collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "One-page executive summary with business outcomes framing.", finalOutputSummary: "Approved with minor tone adjustment.",
    estEffortWithoutAI: 2.5, actualEffortWithAI: 1, reviewCorrectionTime: 0.17, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 1.33,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Document timestamps", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-203", validatedDate: new Date("2026-06-11"), managerComments: "Consistently strong output from this prompt.",
    reusabilityLevel: ReusabilityLevel.ORG_WIDE, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2041", employeeId: "emp-108", submissionDate: new Date("2026-06-14"), activityDate: new Date("2026-06-13"),
    projectId: "proj-6", activityCategoryId: "ps-exec-summary", activitySubcategory: "Internet banking exec summary",
    taskDescription: "Prepare the executive summary for the corporate internet banking proposal.",
    aiToolId: "tool-claude", aiModel: "Claude Sonnet 4.5", promptOrWorkflow: "Used the Executive Summary Generator prompt against the proposal draft.",
    reusablePromptUsed: true, reusablePromptId: "rp-execsummary", collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "One-page executive summary.", finalOutputSummary: "Approved as-is.",
    estEffortWithoutAI: 2.5, actualEffortWithAI: 1, reviewCorrectionTime: 0.17, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 1.33,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Document timestamps", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-203", validatedDate: new Date("2026-06-15"), managerComments: "Reliable prompt output.",
    reusabilityLevel: ReusabilityLevel.ORG_WIDE, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2042", employeeId: "emp-110", submissionDate: new Date("2026-06-18"), activityDate: new Date("2026-06-17"),
    projectId: "proj-5", activityCategoryId: "ps-exec-summary", activitySubcategory: "Digital wallet POC exec summary",
    taskDescription: "Prepare the executive summary for the MobiPay digital wallet POC proposal.",
    aiToolId: "tool-claude", aiModel: "Claude Sonnet 4.5", promptOrWorkflow: "Used the Executive Summary Generator prompt.",
    reusablePromptUsed: true, reusablePromptId: "rp-execsummary", collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "One-page executive summary.", finalOutputSummary: "Approved with 1 figure updated.",
    estEffortWithoutAI: 2.5, actualEffortWithAI: 1.1, reviewCorrectionTime: 0.2, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 1.2,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Document timestamps", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-204", validatedDate: new Date("2026-06-19"), managerComments: "Good use of the shared prompt.",
    reusabilityLevel: ReusabilityLevel.ORG_WIDE, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2043", employeeId: "mgr-203", submissionDate: new Date("2026-06-20"), activityDate: new Date("2026-06-19"),
    projectId: "proj-8", activityCategoryId: "ps-customer-followup", activitySubcategory: "Post-demo follow-up",
    taskDescription: "Draft the post-demo follow-up email summarizing next steps for the unified comms opportunity.",
    aiToolId: "tool-chatgpt", aiModel: "GPT-4o", promptOrWorkflow: "Generated a follow-up email from the demo notes and next-step list.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Follow-up email draft with next steps and timeline.", finalOutputSummary: "Sent with minor greeting edit.",
    estEffortWithoutAI: 1, actualEffortWithAI: 0.33, reviewCorrectionTime: 0.08, iterations: 1,
    qualityBefore: 4, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 0.58,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Email timestamps", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgmt-302", validatedDate: new Date("2026-06-21"), managerComments: "Fine, routine follow-up.",
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2044", employeeId: "emp-111", submissionDate: new Date("2026-06-24"), activityDate: new Date("2026-06-23"),
    projectId: "proj-5", activityCategoryId: "ps-sales-pipeline-research", activitySubcategory: "East Africa pipeline prospects",
    taskDescription: "Research additional prospect accounts in East Africa similar to the MobiPay profile.",
    aiToolId: "tool-perplexity", aiModel: "Sonar Pro", promptOrWorkflow: "Generated a prospect longlist with sector and size filters.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Longlist of 12 prospect accounts.", finalOutputSummary: "5 shortlisted for outreach.",
    estEffortWithoutAI: 4, actualEffortWithAI: 2.5, reviewCorrectionTime: 0.4, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 1.1,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "CRM records", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-204", validatedDate: new Date("2026-06-25"), managerComments: "Good shortlist quality.",
    reusabilityLevel: ReusabilityLevel.TEAM, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2045", employeeId: "emp-112", submissionDate: new Date("2026-06-28"), activityDate: new Date("2026-06-26"),
    projectId: "proj-5", activityCategoryId: "ps-poc-prep", activitySubcategory: "Wallet POC environment prep",
    taskDescription: "Prepare the proof-of-concept environment plan and test data setup for the MobiPay POC.",
    aiToolId: "tool-chatgpt", aiModel: "GPT-4o", promptOrWorkflow: "Generated the POC setup plan and checklist from the technical requirements.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "POC setup checklist with 16 tasks.", finalOutputSummary: "Under review by the delivery lead.",
    estEffortWithoutAI: 10, actualEffortWithAI: 7, reviewCorrectionTime: 1, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 1, defectsAfter: 0, reworkTimeAvoided: 2,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Project-management records", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.UNDER_REVIEW, validatedById: null, validatedDate: null, managerComments: null,
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2046", employeeId: "emp-107", submissionDate: new Date("2026-07-02"), activityDate: new Date("2026-06-30"),
    projectId: "proj-8", activityCategoryId: "ps-prototype-wireframe", activitySubcategory: "Admin console wireframes",
    taskDescription: "Prepare wireframes for the unified comms admin console concept demo.",
    aiToolId: "tool-gemini", aiModel: "Gemini 2.5 Pro", promptOrWorkflow: "Generated wireframe layouts from the feature list for the concept demo.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "6 wireframe screens.", finalOutputSummary: "Approved with navigation adjusted on 1 screen.",
    estEffortWithoutAI: 6, actualEffortWithAI: 4, reviewCorrectionTime: 0.75, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 1.25,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Document revision history", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-203", validatedDate: new Date("2026-07-03"), managerComments: "Good starting point for the concept demo.",
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2047", employeeId: "emp-108", submissionDate: new Date("2026-07-06"), activityDate: new Date("2026-07-04"),
    projectId: "proj-6", activityCategoryId: "ps-case-study", activitySubcategory: "Reference case study",
    taskDescription: "Prepare a reference case study for a similar past banking deployment to support the Gulf Trust Bank pursuit.",
    aiToolId: "tool-claude", aiModel: "Claude Sonnet 4.5", promptOrWorkflow: "Generated the case study narrative from the completed project retrospective notes.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Case study draft with outcomes and metrics.", finalOutputSummary: "Approved with client name anonymized per confidentiality terms.",
    estEffortWithoutAI: 4, actualEffortWithAI: 2.5, reviewCorrectionTime: 0.4, iterations: 1,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 1.1,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Previous versions of similar documents", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-203", validatedDate: new Date("2026-07-07"), managerComments: "Anonymization confirmed correct.",
    reusabilityLevel: ReusabilityLevel.ORG_WIDE, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2048", employeeId: "emp-109", submissionDate: new Date("2026-07-10"), activityDate: new Date("2026-07-08"),
    projectId: "proj-6", activityCategoryId: "ps-tech-architecture-explanation", activitySubcategory: "Architecture walkthrough note",
    taskDescription: "Prepare a plain-language technical architecture explanation for the client procurement committee.",
    aiToolId: "tool-claude", aiModel: "Claude Sonnet 4.5", promptOrWorkflow: "Translated the technical architecture doc into a non-technical explanation.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Plain-language architecture explanation, 2 pages.", finalOutputSummary: "Approved as-is.",
    estEffortWithoutAI: 3, actualEffortWithAI: 1.75, reviewCorrectionTime: 0.25, iterations: 1,
    qualityBefore: 4, qualityAfter: 4, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 1,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Document timestamps", evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-203", validatedDate: new Date("2026-07-11"), managerComments: "Accessible for a non-technical audience.",
    reusabilityLevel: ReusabilityLevel.TEAM, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2049", employeeId: "emp-102", submissionDate: new Date("2026-07-12"), activityDate: new Date("2026-07-11"),
    projectId: "proj-1", activityCategoryId: "ba-crd", activitySubcategory: "Fee schedule change request (resubmission)",
    taskDescription: "Draft the impact section of a Change Request Document for a new fee schedule module.",
    aiToolId: "tool-chatgpt", aiModel: "GPT-4o", promptOrWorkflow: "Used the CRD Section Drafting Template with the existing BRD as context.",
    reusablePromptUsed: true, reusablePromptId: "rp-crd-outline", collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Drafted impact, assumptions and rollback sections.", finalOutputSummary: "Pending review - closely mirrors an earlier submission on the same document.",
    estEffortWithoutAI: 5, actualEffortWithAI: 3, reviewCorrectionTime: 0.75, iterations: 1,
    qualityBefore: 3, qualityAfter: 3, defectsBefore: 2, defectsAfter: 2, reworkTimeAvoided: -0.75,
    finalOutcome: FinalOutcome.ADOPTED_WITH_EDITS, evidenceType: null, evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.DRAFT, validatedById: null, validatedDate: null, managerComments: null,
    reusabilityLevel: ReusabilityLevel.DEPARTMENT, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: ["possible-duplicate-of-OPT-2002"],
  },
  {
    id: "OPT-2050", employeeId: "emp-106", submissionDate: new Date("2026-07-15"), activityDate: new Date("2026-07-14"),
    projectId: "proj-3", activityCategoryId: "ba-req-documentation", activitySubcategory: "Full requirement pack",
    taskDescription: "Document the complete requirement pack for the OSS integration change window.",
    aiToolId: "tool-chatgpt", aiModel: "GPT-4o", promptOrWorkflow: "Generated the full requirement document from a short bullet list of notes.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Full requirement document generated in one pass.", finalOutputSummary: "Claimed as complete and submitted without manager or peer review yet.",
    estEffortWithoutAI: 20, actualEffortWithAI: 1, reviewCorrectionTime: 0, iterations: 1,
    qualityBefore: 3, qualityAfter: 3, defectsBefore: 0, defectsAfter: 0, reworkTimeAvoided: 19,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: null, evidenceFileName: null, supportingLink: null,
    validationStatus: ValidationStatus.SUBMITTED, validatedById: null, validatedDate: null, managerComments: null,
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    flags: ["outlier-high-claim", "missing-evidence"],
  },
  {
    id: "OPT-2051", employeeId: "emp-104", submissionDate: new Date("2026-07-18"), activityDate: new Date("2026-07-17"),
    projectId: "proj-10", activityCategoryId: "ba-diagram", activitySubcategory: "Lending journey diagram",
    taskDescription: "Create a customer-journey diagram for the SME digital lending flow.",
    aiToolId: "tool-whimsical", aiModel: "Whimsical AI Diagrams", promptOrWorkflow: "Generated the journey diagram from the process description.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Journey diagram with 9 steps.", finalOutputSummary: "Needed substantial rework to match the actual approval workflow; saving was negligible once review time is included.",
    estEffortWithoutAI: 3, actualEffortWithAI: 2.8, reviewCorrectionTime: 0.5, iterations: 2,
    qualityBefore: 3, qualityAfter: 3, defectsBefore: 1, defectsAfter: 1, reworkTimeAvoided: -0.3,
    finalOutcome: FinalOutcome.ADOPTED_WITH_EDITS, evidenceType: "Document revision history", evidenceFileName: "lending-journey-v3.pdf", supportingLink: null,
    validationStatus: ValidationStatus.REJECTED, validatedById: "mgr-202", validatedDate: new Date("2026-07-19"), managerComments: "Effort saving is negligible once review time is counted, and reusability is low. Not counting this toward team savings.",
    reusabilityLevel: ReusabilityLevel.NONE, confidentialityClassification: ConfidentialityClassification.INTERNAL,
    flags: [] as string[],
  },
  {
    id: "OPT-2052", employeeId: "emp-107", submissionDate: new Date("2026-06-29"), activityDate: new Date("2026-06-28"),
    projectId: "proj-8", activityCategoryId: "ps-proposal-prep", activitySubcategory: "Hardware proposal (network equipment)",
    taskDescription: "Prepare the hardware/network-equipment proposal for a customer's branch connectivity upgrade, applying the template covered in the COE session two days prior.",
    aiToolId: "tool-claude", aiModel: "Claude Sonnet 4.5", promptOrWorkflow: "Used the standardized hardware proposal template from the COE workshop: fed the requirements list and sizing worksheet into Claude to draft the technical narrative section by section.",
    reusablePromptUsed: false, reusablePromptId: null, collaborationType: CollaborationType.INDIVIDUAL, collaboratorsCount: 1,
    aiOutputSummary: "Full technical narrative and BOM justification drafted from the requirements list.", finalOutputSummary: "Proposal issued to the customer same-day, two pricing lines double-checked against the distributor quote.",
    estEffortWithoutAI: 20, actualEffortWithAI: 5, reviewCorrectionTime: 0.5, iterations: 2,
    qualityBefore: 3, qualityAfter: 4, defectsBefore: 1, defectsAfter: 0, reworkTimeAvoided: 14.5,
    finalOutcome: FinalOutcome.ADOPTED, evidenceType: "Recorded task start and completion times", evidenceFileName: "hardware-proposal-timestamps.png", supportingLink: "https://internal.crm/opportunities/proj-8",
    validationStatus: ValidationStatus.VALIDATED, validatedById: "mgr-203", validatedDate: new Date("2026-06-30"), managerComments: "Matches session template exactly - great example of COE session ROI. Verified against project timeline.",
    reusabilityLevel: ReusabilityLevel.TEAM, confidentialityClassification: ConfidentialityClassification.CONFIDENTIAL,
    coeSessionId: "coe-hardware-proposal-template",
    flags: [] as string[],
  },
];
