import { AssetType, ApprovalStatus } from "../../generated/prisma/client";

export const reusableAssets = [
  { id: "rp-execsummary", title: "Executive Summary Generator (Proposal)", type: AssetType.PROMPT, categoryId: "ps-exec-summary", toolId: "tool-claude", createdById: "lead-bse", createdDate: new Date("2025-11-10"), timesReused: 14, cumulativeHoursSaved: 38, avgRating: 4.6, ratingsCount: 11, status: ApprovalStatus.APPROVED, lastReviewedDate: new Date("2026-05-01") },
  { id: "rp-mom-recap", title: "Meeting-to-MoM Recap Prompt", type: AssetType.PROMPT, categoryId: "ba-mom", toolId: "tool-internal", createdById: "lead-bse", createdDate: new Date("2025-09-01"), timesReused: 46, cumulativeHoursSaved: 34.5, avgRating: 4.8, ratingsCount: 29, status: ApprovalStatus.APPROVED, lastReviewedDate: new Date("2026-06-01") },
  { id: "rp-crd-outline", title: "CRD Section Drafting Template", type: AssetType.TEMPLATE, categoryId: "ba-crd", toolId: "tool-chatgpt", createdById: "lead-bse", createdDate: new Date("2025-10-05"), timesReused: 9, cumulativeHoursSaved: 13.5, avgRating: 3.4, ratingsCount: 7, status: ApprovalStatus.UNDER_REVIEW, lastReviewedDate: new Date("2026-02-19") },
  { id: "rp-rfp-structure", title: "RFP Response Skeleton Workflow", type: AssetType.WORKFLOW, categoryId: "ps-rfp-response", toolId: "tool-claude", createdById: "lead-bse", createdDate: new Date("2025-08-20"), timesReused: 6, cumulativeHoursSaved: 42, avgRating: 4.7, ratingsCount: 6, status: ApprovalStatus.APPROVED, lastReviewedDate: new Date("2026-03-07") },
  { id: "rp-competitor-brief", title: "Competitor Snapshot Prompt", type: AssetType.PROMPT, categoryId: "ps-competitor-comparison", toolId: "tool-perplexity", createdById: "lead-bse", createdDate: new Date("2025-09-15"), timesReused: 11, cumulativeHoursSaved: 22, avgRating: 4.1, ratingsCount: 9, status: ApprovalStatus.APPROVED, lastReviewedDate: new Date("2026-04-01") },
  { id: "rp-testscenario-gen", title: "Test Scenario Generator from Requirements", type: AssetType.PROMPT, categoryId: "ba-test-scenario", toolId: "tool-chatgpt", createdById: "lead-bse", createdDate: new Date("2025-07-01"), timesReused: 19, cumulativeHoursSaved: 26.5, avgRating: 4.5, ratingsCount: 15, status: ApprovalStatus.APPROVED, lastReviewedDate: new Date("2026-01-23") },
  { id: "rp-diagram-flow", title: "Process Flow Diagram Prompt", type: AssetType.PROMPT, categoryId: "ba-process-flow", toolId: "tool-whimsical", createdById: "lead-bse", createdDate: new Date("2025-08-10"), timesReused: 15, cumulativeHoursSaved: 18, avgRating: 4.3, ratingsCount: 12, status: ApprovalStatus.APPROVED, lastReviewedDate: new Date("2026-02-03") },
  { id: "rp-demo-script", title: "Demo Script & Data Builder", type: AssetType.WORKFLOW, categoryId: "ps-demo-prep", toolId: "tool-gamma", createdById: "lead-bse", createdDate: new Date("2025-10-20"), timesReused: 8, cumulativeHoursSaved: 14, avgRating: 4.0, ratingsCount: 6, status: ApprovalStatus.APPROVED, lastReviewedDate: new Date("2026-05-16") },
];
