import { UserGroup } from "../../generated/prisma/client";

// One account per permission tier - no department/team/hourly-cost, since
// with a single account per role there's no org hierarchy to attach and no
// realistic per-person cost figure to maintain. clerkId links each row to a
// real signed-in person (see prisma/scripts/link-clerk-user.ts).
export const users = [
  {
    id: "trainee-bse",
    clerkId: null,
    employeeId: "TRAINEE-BSE",
    email: "trainee.bse@hsenidmobile.com",
    name: "Trainee Business Solutions Engineer",
    jobTitle: "Trainee Business Solutions Engineer",
    userGroup: UserGroup.TRAINEE_BSE,
    country: "Sri Lanka",
    active: true,
    joinedDate: new Date("2026-01-01"),
  },
  {
    id: "associate-bse",
    clerkId: null,
    employeeId: "ASSOCIATE-BSE",
    email: "associate.bse@hsenidmobile.com",
    name: "Associate Business Solutions Engineer",
    jobTitle: "Associate Business Solutions Engineer",
    userGroup: UserGroup.ASSOCIATE_BSE,
    country: "Sri Lanka",
    active: true,
    joinedDate: new Date("2026-01-01"),
  },
  {
    id: "bse",
    clerkId: null,
    employeeId: "BSE",
    email: "muditha.s@hsenidmobile.com",
    name: "Business Solutions Engineer",
    jobTitle: "Business Solutions Engineer",
    userGroup: UserGroup.BSE,
    country: "Sri Lanka",
    active: true,
    joinedDate: new Date("2026-01-01"),
  },
  {
    id: "lead-bse",
    clerkId: null,
    employeeId: "LEAD-BSE",
    email: "lead.bse@hsenidmobile.com",
    name: "Lead Business Solutions Engineer",
    jobTitle: "Lead Business Solutions Engineer",
    userGroup: UserGroup.LEAD_BSE,
    country: "Sri Lanka",
    active: true,
    joinedDate: new Date("2026-01-01"),
  },
  {
    id: "management",
    clerkId: null,
    employeeId: "MANAGEMENT",
    email: "management@hsenidmobile.com",
    name: "Management",
    jobTitle: "Management",
    userGroup: UserGroup.MANAGEMENT,
    country: "Sri Lanka",
    active: true,
    joinedDate: new Date("2026-01-01"),
  },
  {
    id: "admin",
    clerkId: null,
    employeeId: "ADMIN",
    email: "admin@hsenidmobile.com",
    name: "Admin",
    jobTitle: "Platform Administrator",
    userGroup: UserGroup.ADMIN,
    country: "Sri Lanka",
    active: true,
    joinedDate: new Date("2026-01-01"),
  },
];
